accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView

app_name = "accountapp"


urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

accountapp/models.py
from django.db import models

# Create your models here.


# db랑 연결시켜주는것
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from accountapp.models import HelloWorld


def hello_world(request):

    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    template_name = 'accountapp/detail.html'


class AccountUpdateView(UpdateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

  <div style="text-align:center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>

    <div style="text-align:center; max-width: 500px; margin: 4rem auto;">
      <p>
        {{ user.date_joined }}
      </p>
      <h2>
        {{ user.username }}
      </h2>

      {% if target_user == user %}
      <a href="{% url 'accountapp:update' pk=user.pk %}">
        <p>
          Change Info
        </p>
        {% endif %}
      </a>

    </div>
  </div>



{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center">
      <h1 style="font-family: 'Ubuntu', sans-serif;">
          Hello World List!
      </h1>
        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
              {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align:center; max-width: 500px; margin: 4rem auto">
  <div>
        <h4>Login</h4>
  </div>
  <div>
    <form action="" method="post">
      {% csrf_token %}
<!--      {{ form }}-->
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary">
    </form>
  </div>
</div>





{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align:center; max-width: 500px; margin: 4rem auto">
  <div class="mb-4">
    <h4>ChangeInfo</h4>
  </div>
  <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary">
  </form>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}
<body>

    {% include 'header.html' %}

    <hr>
    {% block content %}
    {% endblock %}

    <hr>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div style="text-align:center; margin-top:2rem;">

        <div style="font-size:.8rem;">
            <span>공지사항</span>
            <span>서비스 소개</span>
            <span>제휴문의</span>
        </div>
        <div style="margin-top: 1rem; font-family: 'Ubuntu', sans-serif;">
            <h6>Pragmatic</h6>
        </div>
    </div>

templates/head.html
<head>
  <meta charset="UTF-8">
  <title>Pragmatic</title>


<!--bootstrap link-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!--google fonts link-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@1,300&display=swap" rel="stylesheet">
</head>

templates/header.html
<div style="text-align:center; margin: 2rem 0;">
    <div>
        <h1 style="font-family: 'Ubuntu', sans-serif;">Pragmatic</h1>
    </div>
    <div>
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>login</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>

</div>